2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Configure stats pid to 18224
2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Bobby\.config\wandb\settings
2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Bobby\Akash_Django\R\Droupout2 (another copy)\PFLlib\system\wandb\settings
2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-25 22:02:41,174 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'system\\main.py', 'program_abspath': 'C:\\Users\\Bobby\\Akash_Django\\R\\Droupout2 (another copy)\\PFLlib\\system\\main.py', 'program': 'C:\\Users\\Bobby\\Akash_Django\\R\\Droupout2 (another copy)\\PFLlib\\system\\main.py'}
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:_log_setup():520] Logging user logs to C:\Users\Bobby\Akash_Django\R\Droupout2 (another copy)\PFLlib\system\wandb\run-20240625_220241-y0yab5gu\logs\debug.log
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:_log_setup():521] Logging internal logs to C:\Users\Bobby\Akash_Django\R\Droupout2 (another copy)\PFLlib\system\wandb\run-20240625_220241-y0yab5gu\logs\debug-internal.log
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:init():560] calling init triggers
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:init():610] starting backend
2024-06-25 22:02:41,182 INFO    MainThread:18224 [wandb_init.py:init():614] setting up manager
2024-06-25 22:02:41,182 INFO    MainThread:18224 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-06-25 22:02:41,190 INFO    MainThread:18224 [wandb_init.py:init():622] backend started and connected
2024-06-25 22:02:41,190 INFO    MainThread:18224 [wandb_init.py:init():711] updated telemetry
2024-06-25 22:02:41,332 INFO    MainThread:18224 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-25 22:02:42,249 ERROR   MainThread:18224 [wandb_init.py:init():770] encountered error: you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
2024-06-25 22:02:42,249 ERROR   MainThread:18224 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: you may not log runs directly to your organization, please try using your team entity (Error 400: Bad Request)
2024-06-25 22:02:44,004 WARNING MsgRouterThr:18224 [router.py:message_loop():77] message_loop has been closed
