2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Configure stats pid to 19076
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Bobby\.config\wandb\settings
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Bobby\Akash_Django\R\fl\PFLlib\system\wandb\settings
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'system\\main.py', 'program_abspath': 'C:\\Users\\Bobby\\Akash_Django\\R\\fl\\PFLlib\\system\\main.py', 'program': 'C:\\Users\\Bobby\\Akash_Django\\R\\fl\\PFLlib\\system\\main.py'}
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:_log_setup():520] Logging user logs to C:\Users\Bobby\Akash_Django\R\fl\PFLlib\system\wandb\run-20240630_181555-8equfswi\logs\debug.log
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:_log_setup():521] Logging internal logs to C:\Users\Bobby\Akash_Django\R\fl\PFLlib\system\wandb\run-20240630_181555-8equfswi\logs\debug-internal.log
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:init():560] calling init triggers
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:init():610] starting backend
2024-06-30 18:15:55,625 INFO    MainThread:19076 [wandb_init.py:init():614] setting up manager
2024-06-30 18:15:55,648 INFO    MainThread:19076 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-06-30 18:15:55,648 INFO    MainThread:19076 [wandb_init.py:init():622] backend started and connected
2024-06-30 18:15:55,672 INFO    MainThread:19076 [wandb_init.py:init():711] updated telemetry
2024-06-30 18:15:55,785 INFO    MainThread:19076 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-30 18:15:57,034 ERROR   MainThread:19076 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-30 18:15:57,034 ERROR   MainThread:19076 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-30 18:15:59,243 WARNING MsgRouterThr:19076 [router.py:message_loop():77] message_loop has been closed
